import './globals.css'
import {Inter} from 'next/font/google'
import {LayoutMain} from "@/components/LayoutMain/LayoutMain";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}><LayoutMain>{children}</LayoutMain></body>
        </html>
    )
}
